# ReferenceGrant to allow HTTPRoute in maas-db namespace to reference 
# maas-api service in maas-db namespace
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: maas-api-access
  namespace: maas-db
spec:
  from:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    namespace: maas-db
  to:
  - group: ""
    kind: Service
    name: maas-api
