# OpenShift Route for Key Manager Service
# Directs traffic from OpenShift router to Istio gateway
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: maas-api-route
  namespace: maas-db
  labels:
    app: maas-gateway
  annotations:
    cert-manager.io/issuer-kind: ClusterIssuer
    cert-manager.io/issuer-name: letsencrypt-prod
spec:
  host: maas-api.db.apps.maas2.octo-emerging.redhataicoe.com
  port:
    targetPort: 80
  to:
    kind: Service
    name: inference-gateway-istio
    weight: 100
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Allow
  wildcardPolicy: None
