# Credentials for OAuth2 introspection endpoint
---
apiVersion: v1
kind: Secret
metadata:
  name: oauth2-introspection-credentials
  namespace: maas-db
type: Opaque
stringData:
  clientId: "authorino"
  clientSecret: "not-used"
---
apiVersion: v1
kind: Secret
metadata:
  name: oauth2-introspection-credentials
  namespace: kuadrant-system
type: Opaque
stringData:
  clientId: "authorino"
  clientSecret: "not-used"